// Auto-generated by generate-playlist.py
// Run: python generate-playlist.py
window.__playlist = [
  { src: "ЧВ, feelinsomnia - Свет в окнах вселенной.mp3", name: "Свет в окнах вселенной", artist: "ЧВ, feelinsomnia" },
];
